Vagrant.configure("2") do |config|
    cpu_cap = ENV.has_key?('SRV_CPU_CAP') ? ENV['SRV_CPU_CAP'] : 100
    cpu_num = ENV.has_key?('SRV_CPU_NUM') ? ENV['SRV_CPU_NUM'] : 2
    mem_lim = ENV.has_key?('SRV_MEM_LIM') ? ENV['SRV_MEM_LIM'] : 1536
  
    (1..2).each do |i|
      config.vm.define "server_#{i}" do |server|
        server.vm.box = "ubuntu/focal64"
        server.vm.box_version = "20210125.0.1"
        server.vm.provider "virtualbox" do |v|
          v.customize ["modifyvm", :id, "--cpuexecutioncap", cpu_cap]
          v.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant", "1"]
        end
        server.vm.hostname = "server.localhost"
        server.vm.network "private_network", ip: "192.168.99.10#{i}"
        server.vm.synced_folder ".", "/vagrant", disabled: true
        server.vm.synced_folder "../../", "/vagrant", :mount_options => [
          "dmode=777","fmode=777"
        ], type: "virtualbox"
  
        server.vm.provider "virtualbox" do |v|
          v.memory = mem_lim
          v.cpus = cpu_num
        end
  
        server.vm.provision :shell, inline: "apt update && apt install -qy ansible"
  
        server.vm.provision "ansible_local" do |ansible|
          ansible.playbook = "/vagrant/vm/server/provision/playbook.yml"
          ansible.install_mode = "default"
        end
      end
    end
  end
  