---
- hosts: all
  become: yes
  tasks:
    - name: Full system upgrade
      become: yes
      apt:
        update_cache: yes
        upgrade: yes
    - name: Install CLI apps and libraries
      apt:
        name:
          - build-essential
          - software-properties-common
          - git
          - make
          - htop
          - iotop
          - rsync
        state: latest
    - name: Install MySQL
      apt:
        name:
          - mysql-server
          - python3-pymysql
        state: latest
    - name: MySQL configuration
      template:
        src: ./config-templates/mysqld.j2
        dest: /etc/mysql/mysql.conf.d/mysqld.cnf
        owner: root
        group: root
        mode: '0644'
    - name: Set default MySQL root password
      become: true
      command: mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password'; CREATE USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'password'; GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;"
      ignore_errors: yes
    - name: Restart service MySQL, in all cases
      service:
        name: mysql
        state: restarted
    - name: Install atop
      apt:
        name:
          - atop
        state: latest
    - name: Set Atop settings
      replace:
        path: /usr/share/atop/atop.daily
        regexp: "{{ item.regexp }}"
        replace: "{{ item.replace }}"
        backup: yes
      loop:
        - regexp: INTERVAL=\d+
          replace: INTERVAL=1
        - regexp: LOGGENERATIONS=\d+
          replace: LOGGENERATIONS=2
    - name: Restart Atop service
      service:
        name: atop
        state: restarted
