Vagrant.configure("2") do |config|
    cpu_cap = ENV.has_key?('BLC_CPU_CAP') ? ENV['BLC_CPU_CAP'] : 100
    cpu_num = ENV.has_key?('BLC_CPU_NUM') ? ENV['BLC_CPU_NUM'] : 2
    mem_lim = ENV.has_key?('BLC_MEM_LIM') ? ENV['BLC_MEM_LIM'] : 512
  
    config.vm.box = "ubuntu/focal64"
    config.vm.box_version = "20210125.0.1"
  
    config.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--cpuexecutioncap", cpu_cap]
      v.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant", "1"]
    end
  
    config.vm.hostname = "balancer.localhost"
    config.vm.network "private_network", ip: "192.168.99.111"
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.synced_folder "../../", "/vagrant", :mount_options => [
      "dmode=777","fmode=777"
    ], type: "virtualbox"
  
    config.vm.provider "virtualbox" do |v|
      v.memory = mem_lim
      v.cpus = cpu_num
    end
  
    config.vm.provision :shell, inline: "apt update && apt install -qy ansible"
  
    config.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "/vagrant/vm/balancer/provision/playbook.yml"
      ansible.install_mode = "default"
    end
  end
  
  